const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const state={collection:'demo',live:null,poll:null,askVersion:0};

async function json(url,options){const r=await fetch(url,options);let d={};try{d=await r.json()}catch(_){}if(!r.ok)throw new Error(d.error||`Request failed (${r.status})`);return d}
function safeHttps(value){try{const u=new URL(String(value));return u.protocol==='https:'?u.href:null}catch(_){return null}}
function sourceLink(url,label){const safe=safeHttps(url);return safe?`<a href="${esc(safe)}" target="_blank" rel="noopener noreferrer">${esc(label||safe)} ↗</a>`:''}
function shownDate(value){if(!value)return 'Not checked';const d=new Date(value);return Number.isNaN(d.getTime())?String(value):d.toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'})}
function snapshotAge(d){if(d.snapshot_age)return String(d.snapshot_age);if(Number.isFinite(Number(d.snapshot_age_seconds))){const seconds=Number(d.snapshot_age_seconds);if(seconds<120)return `${Math.round(seconds)} sec`;if(seconds<7200)return `${Math.round(seconds/60)} min`;return `${Math.round(seconds/3600)} hr`}return ''}

function docCard(d,collection){
  if(collection==='live')return `<article class="doc live-doc" data-doc="${esc(d.id)}" data-doc-collection="live"><div class="doc-row"><span class="tag">Live web</span><span class="tag ${esc(d.status)}">${esc(d.status||'unknown')}</span></div><h3>${esc(d.title)}</h3><div class="doc-row"><span>${esc(d.chunks??0)} chunks</span><span>·</span><span>Checked ${esc(shownDate(d.last_checked))}</span></div>${d.error?`<div class="source-error">${esc(d.error)}</div>`:''}</article>`;
  return `<article class="doc" data-doc="${esc(d.id)}" data-doc-collection="demo"><div class="doc-row"><span class="tag">${esc(d.domain)}</span><span class="tag ${esc(d.status)}">${esc(d.status)}</span></div><h3>${esc(d.title)}</h3><div class="doc-row"><span>Effective ${esc(d.effective)}</span><span>·</span><span>${esc(d.id)}</span></div></article>`
}
async function loadDocs(){
  const collection=state.collection;const box=$('#documents');box.innerHTML='<div class="docs-loading">Loading sources…</div>';
  try{const suffix=collection==='live'?'?collection=live':'';const d=await json('/api/documents'+suffix);if(collection!==state.collection)return;const docs=d.documents||[];box.innerHTML=docs.length?docs.map(item=>docCard(item,collection)).join(''):`<div class="docs-loading">${collection==='live'?'No live sources have been indexed yet. Open Live sources to refresh the configured allowlist.':'No documents found.'}</div>`;$('#library-stats').innerHTML=`<span><b>${docs.length}</b> documents</span><span><b>${collection==='live'?'LIVE':'DEMO'}</b> collection</span>`}catch(e){if(collection===state.collection)box.innerHTML=`<div class="docs-loading error-text">${esc(e.message)}</div>`}
}
function citation(c,collection){
  const link=collection==='live'&&c.source_url?sourceLink(c.source_url,'Open source'):'';const meta=collection==='live'?`${c.fetched_at?`Fetched ${esc(shownDate(c.fetched_at))}`:''}${link?` · ${link}`:''}`:`${esc(c.effective)} · ${esc(c.status)}`;const warning=c.error||c.source_error||(c.stale?'Cached snapshot may be stale.':'');
  return `<article class="citation" data-doc="${esc(c.doc_id)}" data-doc-collection="${collection}"><div class="cite-top"><span class="cite-id">[${esc(c.id)}] ${esc(c.heading)}</span><span>${meta}</span></div><blockquote>“${esc(c.text)}”</blockquote>${warning?`<div class="citation-warning">${esc(warning)}</div>`:''}</article>`
}
function renderResult(d,requestedCollection){const collection=d.collection==='live'?'live':requestedCollection;const label={answered:'Supported answer',conflict:'Version conflict',abstained:'Not enough evidence'}[d.status]||'Answer';const age=snapshotAge(d);$('#result').className='result';$('#result').innerHTML=`<div class="result-head"><span class="status ${esc(d.status)}">${esc(label)}</span><span class="confidence">Retrieval score ${Math.round(Number(d.confidence||0)*100)}% · ${esc(d.retrieval_mode||d.mode)}${age?` · snapshot ${esc(age)} old`:''}</span></div>${d.generation_warning?`<div class="notice">${esc(d.generation_warning)}</div>`:''}<p class="answer">${esc(d.answer)}</p>${d.status==='conflict'?'<div class="notice"><strong>Check before acting.</strong> The sources contain different dated rules; the current office is the authority.</div>':''}${(d.citations||[]).length?`<div class="citation-label">Evidence excerpts · click to inspect source</div>${d.citations.map(c=>citation(c,collection)).join('')}`:`<div class="notice">No excerpt cleared the evidence threshold. The system intentionally did not guess.</div>`}`}

function setCollection(collection){
  state.collection=collection;state.askVersion++;$$('[data-collection]').forEach(b=>b.classList.toggle('active',b.dataset.collection===collection));
  const live=collection==='live';$('#question').placeholder=live?'What computing programmes does GLS University offer?':'Can my friend stay in my residence hall for three nights?';$('#library-description').textContent=live?'Configured public pages fetched by the local sync service.':'Fictional demo policies for a deterministic walkthrough.';$('#eval-wrap').classList.toggle('hidden',live);$('#active-collection').textContent=live?'Searching refreshed live sources':'Searching fictional demo policies';$('#mode-badge').innerHTML=live?'<span></span> Live collection':'<span></span> Demo · lexical';
  $('#result').className='result empty';$('#result').innerHTML=live?'<div class="assistant-avatar">↻</div><div><h2>Live sources selected</h2><p>Answers now use only the configured, refreshed public sources. Check sync status before relying on recent changes.</p></div>':'<div class="assistant-avatar">✦</div><div><h2>Fictional demo policies selected</h2><p>Use the authored examples to inspect citations, conflicts, and abstention behavior.</p></div>';
  const prompts=live?[['What programmes does the Faculty of Computer Applications and Information Technology offer?','Programmes'],['What are the admission announcements for GLS University?','Announcements'],['Which BCA MCA syllabus documents are listed?','Syllabus']]:[['When is the deadline to drop a full-term course?','Drop deadline'],['How do I reset a forgotten campus password?','Password reset'],['Can my friend stay in my dorm for three nights?','Overnight guest']];$$('.examples [data-q]').forEach((button,index)=>{button.dataset.q=prompts[index][0];button.textContent=prompts[index][1]});$('#footer-note').textContent=live?'Unofficial portfolio demo · Answers use configured public-page snapshots · No student data stored':'Unofficial portfolio demo · Fictional policy content · No student data stored';
  loadDocs();if(live)loadLiveStatus(false)
}

$('#ask-form').addEventListener('submit',async e=>{e.preventDefault();const q=$('#question').value.trim();if(!q)return;const collection=state.collection;const requestVersion=++state.askVersion;$('#result').className='result loading';$('#result').innerHTML=`<p class="answer">Searching the ${collection==='live'?'live source':'fictional demo'} collection…</p>`;try{const d=await json('/api/ask',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q,mode:$('#ollama').checked?'ollama':'offline',collection})});if(requestVersion===state.askVersion&&collection===state.collection)renderResult(d,collection)}catch(e){if(requestVersion===state.askVersion&&collection===state.collection)$('#result').innerHTML=`<div class="notice">${esc(e.message)}</div>`}finally{if(requestVersion===state.askVersion&&collection===state.collection)$('#result').classList.remove('loading')}});

async function openDocument(id,collection){
  try{const suffix=collection==='live'?'?collection=live':'';const d=await json('/api/documents/'+encodeURIComponent(id)+suffix);$('#viewer-title').textContent=d.title||'Source document';const live=collection==='live';const link=live?sourceLink(d.url||d.source_url,'Open original source'):'';$('#viewer-meta').innerHTML=live?`<span class="tag">Live web</span><span class="tag ${esc(d.status)}">${esc(d.status||'unknown')}</span><span>Fetched ${esc(shownDate(d.fetched_at||d.last_checked))}</span>${link?`<span>${link}</span>`:''}`:`<span class="tag">${esc(d.domain)}</span><span class="tag ${esc(d.status)}">${esc(d.status)}</span><span>Published ${esc(d.published)}</span><span>Effective ${esc(d.effective)}</span><span>${esc(d.office)}</span>`;const sections=Array.isArray(d.sections)?d.sections:[];const warning=d.error||d.source_error||(d.stale?'This viewer is showing a cached snapshot that may be stale.':'');$('#viewer-body').innerHTML=(warning?`<div class="notice">${esc(warning)}</div>`:'')+`<p>${esc(d.summary||'')}</p>`+sections.map(s=>`<section><h3>${esc(s.heading)} <small>[${esc(s.id)}]</small></h3><p>${esc(s.text)}</p></section>`).join('');$('#viewer').showModal()}catch(e){$('#result').innerHTML=`<div class="notice">${esc(e.message)}</div>`}
}
document.addEventListener('click',e=>{if(e.target.closest('a[href]'))return;const example=e.target.closest('[data-q]');if(example){$('#question').value=example.dataset.q;$('#ask-form').requestSubmit();return}const collection=e.target.closest('[data-collection]');if(collection){setCollection(collection.dataset.collection);return}const source=e.target.closest('[data-doc]');if(source)openDocument(source.dataset.doc,source.dataset.docCollection||state.collection)});
$('#close-dialog').onclick=()=>$('#viewer').close();
$('#search-live').onclick=()=>{setCollection('live');clearTimeout(state.poll);$('#live-manager').close();$('#question').focus()};

function renderLiveStatus(d){
  state.live=d;const embedding=d.embedding||{};const semantic=Boolean(embedding.enabled&&embedding.available);$('#engine-mode').textContent=semantic?`Semantic · ${embedding.model||'embedding model'}`:'Lexical fallback';$('#engine-note').textContent=semantic?'Embedding model is configured and available.':(embedding.message||'Embeddings are disabled or unavailable; lexical retrieval remains active.');$('#sync-interval').textContent=d.auto_refresh_minutes?`Every ${d.auto_refresh_minutes} min`:'Manual only';$('#refresh-feedback').textContent=d.refreshing?'Refresh in progress…':(d.refresh_error?`Last refresh: ${d.refresh_error}`:`Last status check ${new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}`);$('#refresh-live').disabled=Boolean(d.refreshing);$('#refresh-live').textContent=d.refreshing?'Refreshing…':'Refresh sources now';const sources=d.sources||[];$('#live-sources').innerHTML=sources.length?sources.map(s=>{const link=sourceLink(s.url,s.url);return `<article class="source-status"><div class="source-state ${esc(s.status)}"></div><div><h3>${esc(s.title)}</h3>${link?`<p>${link}</p>`:''}<small>Checked ${esc(shownDate(s.last_checked))} · ${esc(s.chunks??0)} chunks${s.last_changed?` · Changed ${esc(shownDate(s.last_changed))}`:''}</small>${s.error?`<div class="source-error">${esc(s.error)}</div>`:''}</div><span class="source-status-label">${esc(s.status||'unknown')}</span></article>`}).join(''):'<div class="docs-loading">No configured live sources were reported.</div>';if(state.collection==='live'){$('#mode-badge').innerHTML=`<span></span> ${semantic?'Live · semantic':'Live · lexical'}`}}
async function loadLiveStatus(poll=true){try{const d=await json('/api/live/status');renderLiveStatus(d);if(d.refreshing&&poll){clearTimeout(state.poll);state.poll=setTimeout(()=>loadLiveStatus(true),1800)}else if(!d.refreshing&&state.collection==='live')loadDocs()}catch(e){$('#refresh-feedback').textContent=e.message;$('#live-sources').innerHTML=`<div class="docs-loading error-text">${esc(e.message)}</div>`}}
$('#open-live').onclick=()=>{$('#live-manager').showModal();loadLiveStatus(true)};$('#close-live').onclick=()=>{clearTimeout(state.poll);$('#live-manager').close()};$('#refresh-live').onclick=async()=>{const button=$('#refresh-live');button.disabled=true;button.textContent='Starting…';$('#refresh-feedback').textContent='Requesting a background refresh…';try{await json('/api/live/refresh',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});await loadLiveStatus(true)}catch(e){$('#refresh-feedback').textContent=e.message;button.disabled=false;button.textContent='Refresh sources now'}};

$('#eval-button').onclick=async()=>{const b=$('#eval-button');b.textContent='Running demo evaluation…';try{const d=await json('/api/evaluate');const s=d.summary;$('#eval').classList.remove('hidden');$('#eval').innerHTML=`<h3>Authored demo regression evaluation</h3><span class="score">${s.correct}/${s.total}</span><p>Exact behavior + expected-source accuracy</p>${Object.entries(s.by_category).map(([k,v])=>`<div><small>${esc(k.replace('_',' '))} · ${v.correct}/${v.total}</small><div class="bar"><i style="width:${Number(v.accuracy)*100}%"></i></div></div>`).join('')}<small>Fictional demo collection only. Deterministic authored questions are not an independent benchmark.</small>`}catch(e){$('#eval').classList.remove('hidden');$('#eval').textContent=e.message}finally{b.textContent='Run 30-question evaluation ↗'}};

loadDocs();
